#!/usr/bin/env python
"""
Print the solution to a given problem.

This script reduces the amount of boilerplate that we need to write a solution.
Otherwise, we are stuck with `if __name__ == '__main__': print(...)` in every file.
"""

import importlib
import os
import sys

import project
from helpers import import_file, print_error

USAGE = "Usage: script/solution PROBLEM_NUMBER"

def try_int(s):
    try:
        return int(s)
    except ValueError:
        return None

def main(args):
    try:
        if len(args) != 2:
            print_error("Incorrect number of arguments passed")
            print_error(USAGE)
            return 1

        problem_number = try_int(args[1])
        if problem_number is None or problem_number <= 0:
            print_error(f"'{args[1]}' is not a valid problem number.")
            return 2

        # Look up the file containing the solution for the problem
        # and import it dynamically.
        # Expect all solution modules to have a function named `solution()`.
        # Call this function and print the result.
        solutions = project.index_solutions(project.root)

        solution_file = solutions.get(problem_number)
        if solution_file is None:
            print_error(f"No solution file found for Problem {problem_number}.")
            return 3

        problem = import_file("problem", solution_file)
        print(problem.solution())

        return 0
    except Exception as e:
        print_error(e)
        return -1

if __name__ == "__main__":
    exit(main(sys.argv))