#!/usr/bin/env python

import importlib
import os
import sys

import project
from helpers import import_file, print_error, try_int

USAGE = "Usage: script/solution PROBLEM_NUMBER"

def main(args):
    try:
        if len(args) != 2:
            print_error("Incorrect number of arguments passed")
            print_error(USAGE)
            return 1

        problem_number = try_int(args[1])
        if problem_number is None:
            print_error(f"Could not parse '{args[1]}' as a problem number")
            return 2

        solutions = project.index_solutions(project.root)

        solution_dir = solutions.get(problem_number)
        solution_file = os.path.join(solution_dir, "solution.py")
        solution = import_file('solution', solution_file)
        print(solution.solution())

        return 0
    except Exception as e:
        print_error(e)
        return -1

if __name__ == "__main__":
    exit(main(sys.argv))