#!/usr/bin/env python

"""
Automatically regression test all solved problems.

Solved problems should have a script called 'test.py' that runs tests for that problem,
at minimum verifying the correct answer.
This script assumes it lives in the project root.
"""

import os
import sys

import project
from helpers import print_error
from project import InDirectory

def main():
    # Test core
    core_tests = os.path.join(project.root, 'core', 'tests')
    junit_xml = os.path.join(project.root, 'junit-xml', 'core.xml')
    exit_code = os.system(f'pytest {core_tests} --junit-xml={junit_xml}')
    if exit_code != 0:
        print_error(f'pytest {core_tests} failed with exit code {exit_code}')

    # Test problems
    euler = os.path.join(project.root, 'euler')
    os.chdir(euler)

    num_errors = 0
    for problem in sorted(os.listdir()):
        try:
            with InDirectory(problem):
                name = os.path.join(problem, 'solution.py')
                print(f'Running {name} ...')
                exit_code = os.system('python solution.py')
                if exit_code != 0:
                    num_errors += 1
                    print_error(f'Running {name} failed with exit code {exit_code}')
                print()

                name = os.path.join(problem, 'test.py')
                print(f'Testing {name} ...')
                junit_xml = os.path.join(project.root, 'junit-xml', f'test_{problem}.xml')
                exit_code = os.system(f'pytest test.py --junit-xml={junit_xml}')
                if exit_code != 0:
                    num_errors += 1
                    print_error(f'Testing {name} failed with exit code {exit_code}')
                print()
        except Exception as e:
            num_errors += 1
            print_error(f'While processing {problem}, encountered {e}')
    return num_errors

if __name__ == '__main__':
    exit(main())
