name: CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Set up the environment
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Bootstrap the dev environment
      run: source dev-env.sh

    # Make sure we haven't broken any scripts
    - name: Smoke test the dev scripts
      run: |
        source dev-env.sh
        script/solution 1

    # Run static analysis
    - name: Run typechecking
      run: |
        source dev-env.sh
        make typecheck

    - run: make tests