name: CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Set up the environment
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - run: python -m pip install --upgrade pip
    - run: pip install -r requirements.txt

    # Make sure we haven't broken any scripts
    - name: Smoke test dev-env
      run: |
        source dev-env.sh
        script/solution 1

    # Run regression tests
    - run: pytest